### ISSUE TITLE
Go vendor support

### ISSUE THREAD

**Issue by tkurylek** [cloudfoundry/go-buildpack#40]
Hi there. We are using govendor as package management tool. We are wondering if you have any plans to support it? Currently we need to remove `vendor/vendor.json` file so the compilation step succeeds. Otherwise we get:
```
ERR  !     
ERR  !     Error: Cloud Foundry does not support the govendor package manager
ERR  !     We currently only support the 'Godep' package manager for go apps
ERR  !     For support please file an issue: https://github.com/cloudfoundry/go-buildpack/issues
ERR  !   
```
The message is very explicit. Could you tell us why the buildpack checks for `vendor.json` file? Would it be possible to omit this check and go with the native go vendoring instead?
   
I can see that buildpack from Heroku already has it covered:
https://github.com/heroku/heroku-buildpack-go/blob/master/bin/compile

**Comment by davidjahn** [comment]
@tkurylek We have no plans at the moment to support `govendor`, but we do support native go package management in the `vendor/` directory.

To clarify, does your app push successfully when you remove `vendor/vendor.json`  or add it to `.cfignore` and follow [the instructions](http://docs.cloudfoundry.org/buildpacks/go/index.html#pushing_Apps_with_native_Go_vendoring) for pushing apps with native go vendoring?

If it works without `vendor/vendor.json` then, yes, it is a bug in the buildpack and we will try to push a fix to the buildpack within a week.

As an aside, we chose to only support `Godep` explicitly as a package manager because, now that Go has a standard native vendoring system for the `vendor/` directory, it should in principle be possible to push any app using that system rather than the particularities of any given package manager.

**Comment by Dannyzen** [comment]
Thanks @davidjahn! @tkurylek I'm curious as to why your team has decided to use govendor. If you could share with us the value you find in it that would be very helpful!

**Comment by tkurylek** [comment]
Hi @davidjahn 
Thanks for the response. Yes, our app push works after removing `vendor/vendor.json` which makes the check for this file in `/bin/compile` pointless. Do you need me to create a separate issue for that?

Hi @Dannyzen 
We've got tired of godep. We really liked the wrapper commands, easiness of package version upgrade and also `govendor list` command that gives us more control of what is in `/vendor` directory and what is not.

**Comment by davidjahn** [comment]
@tkurylek No need to create a separate issue on github. I have created an issue in the buildpack team's tracking system:

https://www.pivotaltracker.com/story/show/119184383

We will prioritize this issue soon and let you know as soon as we push a fix!

**Comment by davidjahn** [comment]
@tkurylek Our [new release](https://github.com/cloudfoundry/go-buildpack/releases/tag/v1.7.8) has removed the error for govendor, and you should be able to push govendor apps without deleting `vendor/vendor.json` ! You can test out the new go-buildpack with

```
cf push my_app -b https://github.com/cloudfoundry/go-buildpack
```

I am going to close this issue because I believe it is fixed, but could you let us know if we have solved your problem? Thank you for bringing the issue to our attention!

**Comment by tkurylek** [comment]
@davidjahn Sorry for the late response. We've upgraded the buildpack and everything works perfectly. Thank you.
