### ISSUE TITLE
Cannot push golang app

### ISSUE THREAD

**Issue by CodeClinch** [cloudfoundry/go-buildpack#98]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf Version 6.48.0+ca3deaa94.2019-12-04

What version of the buildpack you are using?
Go Buildpack version 1.9.3

If you were attempting to accomplish a task, what was it you were attempting to do?
Trying to push a new app with the following manifest

I implemented an app with go-swagger. The main function is in package /cmd/ca-server/main.go

1) without a command specified: 
---
applications:
  - name: ca-go
    buildpacks: 
    - go_buildpack
    memory: 32M
    instances: 1
    env:
      GoVersion: go1.13.5
      GOPACKAGENAME: <package>/ca
      GO_INSTALL_PACKAGE_SPEC: <package>/ca/cmd/ca-server

--> App will start, but since there is no port specified the app crashes because a random port is used.

OUT Downloading droplet...
OUT Downloaded droplet (10.3M)
OUT Starting health monitoring of container
ERR 2019/12/20 21:55:14 Serving ca at http://127.0.0.1:8080
[CELL/SSHD/0] OUT Exit status 0
[APP/PROC/WEB/0] OUT Exit status 0

2) with command
---
applications:
  - name: ca-go
    buildpacks: 
    - go_buildpack
    memory: 32M
    instances: 1
    command: ./cmd/ca-server/main --port=8080
    env:
      GoVersion: go1.13.5
      GOPACKAGENAME: <package>/ca
      GO_INSTALL_PACKAGE_SPEC: <package>/ca/cmd/ca-server
            
--> App crashes because the main file is not found.

[CELL/0] OUT Downloading droplet...
[CELL/0] OUT Downloaded droplet
[CELL/0] OUT Starting health monitoring of container
ERR bash: <package>/cmd/ca-server/main: No such file or directory
[APP/PROC/WEB/0] OUT Exit status 127

What did you expect to happen?
Running app on CF

3) with port as env variable
---
applications:
  - name: ca-go
    buildpacks: 
    - go_buildpack
    memory: 32M
    instances: 1
    env:
      GoVersion: go1.13.5
      GOPACKAGENAME: <package>/ca
      GO_INSTALL_PACKAGE_SPEC: <package>/ca/cmd/ca-server
      PORT: 8080

--> Cannot push
The app is invalid: environment_variables cannot set PORT

What was the actual behavior?
The following command-line statements should be reflected in the manifest file:
go run cmd/ca-server/main.go --port=8080

or

go build cmd/ca-server/main.go
./main --port=8080

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by thitch97** [comment]
@CodeClinch It looks like there might be a couple of issues here:

1) The $PORT environment variable is provided by the platform, which is why you aren't allowed to set it in your manifest. It also means that it won't be passed as a command-line flag to your program. You will either need to have your program read from the environment or include a start command like `ca-server --port=$PORT`.

2) The name of the binary created during the build process is not `main` and so would not be available at `/ca/cmd/ca-server/main`. Instead, I believe that the binary would be called `ca-server`, meaning that a start command would look like `ca-server`. Here is an [example app](https://github.com/cloudfoundry/go-buildpack/tree/master/fixtures/install_pkg_spec_go_modules) that shows how you might achieve this.

I'm going to close this issue. Feel free to reopen this if you need further assistance.
